CREATE TABLE `OSM_TAGS`
(
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VERSION` int(11) DEFAULT NULL,

  `P_ID` bigint(20) DEFAULT NULL,
  `P_TABLE` varchar(80) DEFAULT NULL,
  `D_KEY` varchar(30) DEFAULT NULL,
  `D_VAL` varchar(80) DEFAULT NULL,
  `VALID` bit(1) DEFAULT NULL,

  PRIMARY KEY(`ID`)
)
DEFAULT CHARSET=utf8;
