ALTER TABLE `OSM_PLACES` add `CREATION_TIME`     datetime DEFAULT NOT NULL;
ALTER TABLE `OSM_PLACES` add `MODIFICATION_TIME` datetime DEFAULT NOT NULL;

UPDATE `OSM_PLACES` set `CREATION_TIME` = NOW()     where `CREATION_TIME` IS NULL;
UPDATE `OSM_PLACES` set `MODIFICATION_TIME` = NOW() where `MODIFICATION_TIME` IS NULL;
